#!/bin/sh

# This script automatically gets information about popular open source licenses, through the GitHub
# API. This is a tool for developers of this project generator. Regular users, by cloning the
# repository, should already have these licenses installed.
#
# ./licenses.sh build - create licenses directory
# ./licenses.sh clean - delete cache directories

# Copyright 2023 Humberto Gomes
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

OUTPUT_DIR="licenses"
TMP_DIR="/tmp/new-project"

# Makes sure the script has access to all dependencies it needs to work.
assert_dependencies() {
	if ! command -v jq > /dev/null; then
		echo "jq need to be installed and in \$PATH. Leaving ..." >&2
		exit 1
	fi

	if ! command -v curl > /dev/null; then
		echo "curl need to be installed and in \$PATH. Leaving ..." >&2
		exit 1
	fi
}

# Creates a directory, but exits the script if the directory already exists and isn't empty.
mkdir_not_empty() {
	if [ -d "$1" ] && [ -n "$(ls -A "$1")" ]; then
		printf "%s already exists and isn't empty. You can clear the cache with " "$1" >&2
		echo "./licenses.sh clean. Leaving ..." >&2
		exit 1
	elif ! mkdir -p "$1"; then
		echo "mkdir -p $1 failed. Leaving ..." >&2
		exit 1
	fi
}

# Performs a GitHub API request, leaving the program on failure.
# $1 - Request URL is "https://api.github.com/$1"
# $2 - Path to the output file
github_request() {
	if ! curl -so "$2" "https://api.github.com/$1"; then
		echo "curl failed while (https://api.github.com/$1). Leaving ..." >&2
		exit 1
	fi

	if grep -q "rate limit" "$2"; then
		echo "GitHub API rate limit exceeded. Leaving ..." >&2
		exit 1
	fi
}

# Downloads licenses from the GitHub API.
download_license_data() {
	# Licenses that this program knowns and was tested with.
	known_licenses=" agpl-3.0 apache-2.0 bsd-2-clause bsd-3-clause bsl-1.0 cc0-1.0 epl-2.0 gpl-2.0 gpl-3.0 lgpl-2.1 mit mpl-2.0 unlicense "

	echo "Downloading licenses from GitHub API ..."
	mkdir_not_empty "$TMP_DIR/licenses"
	github_request "licenses" "$TMP_DIR/licenses.json"

	for key in $(jq -r ".[].key" "$TMP_DIR/licenses.json"); do
		github_request "licenses/$key" "$TMP_DIR/licenses/$key"

		if ! echo "$known_licenses" | grep -q " $key "; then
			echo "Unrecognized license \"$(jq -r ".name" "$TMP_DIR/licenses/$key")\"." \
			     "Please warn the developer to update the program!"
		fi
	done
}

# Creates all the needed subdirectories in $OUTPUT_DIR, along with a README warning, telling that
# the files in $OUTPUT_DIR are autogenerated.
create_output_directory_structure() {
	mkdir_not_empty "$OUTPUT_DIR/names"
	mkdir_not_empty "$OUTPUT_DIR/headers"
	mkdir_not_empty "$OUTPUT_DIR/bodies"

	{
		echo "# Licenses" ;
		echo "" ;
		echo "These license files were autogenerated by [licenses.sh](../licenses.sh), by" ;
		printf "getting data from the " ;
		echo "[GitHub API](https://docs.github.com/en/rest/licenses/licenses)." ;
	} > "$OUTPUT_DIR/README.md"
}

# Generates the human-readable names of licenses in $OUTPUT_DIR/names, from previously downloaded
# license information.
generate_license_names() {
	echo "Generating license names ..."
	for license in "$TMP_DIR/licenses"/*; do
		jq -r ".name" "$license" > "$OUTPUT_DIR/names/$(basename "$license")"
	done
}

# Generates the licenses bodies in $OUTPUT_DIR/bodies, from previously downloaded license information.
generate_license_bodies() {
	echo "Generating license bodies ..."
	for license in "$TMP_DIR/licenses"/*; do
		jq -r ".body[:-1]" "$license" > "$OUTPUT_DIR/bodies/$(basename "$license")"
	done
}

# Generates license headers for files.
generate_license_headers() {

	# Generates a header from a range of lines in a license.
	# $1 - name of the license file (no directory)
	# $2 - start line (inclusive)
	# $3 - end line (inclusive)
	# $4 - command to run before saving (indentation removal, text replacement, ...). Leave empty
	#      for removal of all indentation.
	header_from_lines() {
		if ! [ -f "$TMP_DIR/licenses/$1" ]; then
			echo "License \"$1\" has been removed from the GitHub API. Please warn the" \
			     "developer to update the program!"
			return 1
		fi

		if [ -z "$4" ]; then
			final_command="sed -r 's/^\\s+//'"
		else
			final_command="$4"
		fi

		jq -r ".body" "$TMP_DIR/licenses/$1" | \
			tail -n "+$2" | head -n "$(($3 - $2 + 1))" | eval "$final_command" \
			> "$OUTPUT_DIR/headers/$1"
	}

	# Command used to format (A/L)GPL licenses
	gpl_command() {
		sed -re 's/^\s+//; s/<year>/[year]/g; s/<name of author>/[fullname]/g ; 1s/.*/[description]/g'
	}

	# Command used to format the Apache license
	apache_command() {
		sed -re 's/^   //g; s/\[yyyy\]/[year]/g; s/\[name of copyright owner\]/[fullname]/g'
	}

	echo "Generating license headers for source files ..."

	header_from_lines "agpl-3.0" 632 646 gpl_command
	header_from_lines "apache-2.0" 189 201 apache_command

	{
		echo "          Copyright [fullname] [year]." ;
		echo "Distributed under the Boost Software License, Version 1.0." ;
		echo "   (See accompanying file LICENSE_1_0.txt or copy at" ;
		echo "         https://www.boost.org/LICENSE_1_0.txt)" ;
	} > "$OUTPUT_DIR/headers/bsl-1.0"

	header_from_lines "gpl-2.0" 293 308 gpl_command
	header_from_lines "gpl-3.0" 634 648 gpl_command
	header_from_lines "lgpl-2.1" 473 489 gpl_command
	header_from_lines "mpl-2.0" 358 360

	# Warning for missing headers
	echo "You can add a custom license file header to licenses that don't contain one. Check" \
	     "\"$OUTPUT_DIR/headers\". Here are those licenses:"
	echo ""

	for license in "$OUTPUT_DIR/names"/*; do
		if ! [ -f "$OUTPUT_DIR/headers/$(basename "$license")" ]; then
			cat "$license"
		fi
	done
}

if [ "$#" -eq 1 ] && [ "$1" = "clean" ]; then
	rm -r "$OUTPUT_DIR" "$TMP_DIR"
elif [ "$#" -eq 1 ] && [ "$1" = "build" ]; then
	assert_dependencies
	#download_license_data
	create_output_directory_structure

	generate_license_names
	generate_license_bodies
	generate_license_headers
else
	echo "Unknown command line arguments! Usage:"
	echo "./licenses.sh build - create licenses directory"
	echo "./licenses.sh clean - delete cache directories"
fi
